# Generated by Django 5.1.3 on 2025-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='unp',
            field=models.CharField(default='123456789', editable=False, max_length=9, verbose_name='УНП компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('0', 'создан'), ('1', 'в работе'), ('2', 'ошибка при отправке'), ('3', 'отправлен'), ('4', 'закрыт')], default='0', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
