# Generated by Django 4.1 on 2025-02-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='gross_weight',
            field=models.FloatField(verbose_name='Вес брутто'),
        ),
    ]
