# Generated by Django 4.1 on 2025-02-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notice_gross_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
