# Generated by Django 5.1.3 on 2025-01-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notice_unp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='unp',
            field=models.CharField(default='591489147', editable=False, max_length=15, verbose_name='УНП компании'),
        ),
    ]
