# Generated by Django 5.1.3 on 2025-01-16 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_alter_notice_unp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('navigate', 'Переход'), ('close', 'Закрытие')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание действия')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия пользователя',
                'verbose_name_plural': 'Логи действий пользователей',
            },
        ),
    ]
