# Generated by Django 5.1.3 on 2025-01-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('close', 'Закрытие')], max_length=20, verbose_name='Действие'),
        ),
    ]
