# Generated by Django 4.1 on 2025-02-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notice_napravl_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес брутто'),
        ),
    ]
