# Generated by Django 5.1.3 on 2025-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_useractionlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='action_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание действия пользователя'),
        ),
    ]
