# Generated by Django 5.1.3 on 2025-01-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_useractionlog_action_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='purpose_placement',
            field=models.CharField(choices=[('10', 'Выгрузка (прибытие на склад) товара'), ('11', 'Загрузка (убытие со склада) товара')], default='10', max_length=2, verbose_name='Цель размещения'),
        ),
    ]
