# Generated by Django 4.1 on 2025-02-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_notice_napravl_ts_notice_direction_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер прицепа'),
        ),
    ]
