# Generated by Django 4.1 on 2025-02-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_logbook_trailer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_pack',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.place'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=13, unique=True, verbose_name='Код товара (EAN-13)'),
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itf14', models.CharField(max_length=14, unique=True, verbose_name='Штрихкод ITF-14')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('datetime_in', models.DateTimeField(verbose_name='Время прибытия')),
                ('datetime_out', models.DateTimeField(blank=True, null=True, verbose_name='Время убытия')),
                ('current_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущий вес (т)')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальный вес (т)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='core.place')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.pallet'),
        ),
    ]
