# Generated by Django 4.1 on 2025-02-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_product_barcode_remove_product_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logplace',
            name='barcode_type',
            field=models.CharField(choices=[('EAN-13', 'EAN-13'), ('ITF-14', 'ITF-14')], default='EAN-13', max_length=10, verbose_name='Тип штрихкода'),
        ),
        migrations.AddField(
            model_name='logplace',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_places', to='core.pallet', verbose_name='Паллет'),
        ),
        migrations.AddField(
            model_name='logplace',
            name='status',
            field=models.CharField(choices=[('Перемещено', 'Перемещено'), ('Готово к отгрузке', 'Готово к отгрузке'), ('Отгружено', 'Отгружено')], default='Перемещено', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='logplace',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (т)'),
        ),
        migrations.AlterField(
            model_name='logplace',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_places', to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='logplace',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество перемещаемого товара/паллета'),
        ),
    ]
