# Generated by Django 4.1 on 2025-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_logplace_barcode_type_logplace_pallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
