# Generated by Django 4.1 on 2025-02-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pallet_barcode_image_product_barcode_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pallet',
            options={'verbose_name': 'Паллет', 'verbose_name_plural': 'Паллеты'},
        ),
        migrations.RenameField(
            model_name='pallet',
            old_name='itf14',
            new_name='sku_pallet',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='sku_product',
        ),
    ]
