# Generated by Django 4.1 on 2025-02-18 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pallet_options_rename_itf14_pallet_sku_pallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название перевозчика')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактная информация')),
            ],
        ),
        migrations.AddField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('Ожидает приемки', 'Ожидает приемки'), ('На складе', 'На складе'), ('Зарезервировано', 'Зарезервировано'), ('Готово к отгрузке', 'Готово к отгрузке'), ('Отгружено', 'Отгружено')], default='Ожидает приемки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Ожидает приемки', 'Ожидает приемки'), ('На складе', 'На складе'), ('Зарезервировано', 'Зарезервировано'), ('Готово к отгрузке', 'Готово к отгрузке'), ('Отгружено', 'Отгружено')], default='Ожидает приемки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.supplier'),
        ),
        migrations.AlterField(
            model_name='logplace',
            name='status',
            field=models.CharField(choices=[('Ожидает приемки', 'Ожидает приемки'), ('На складе', 'На складе'), ('Зарезервировано', 'Зарезервировано'), ('Готово к отгрузке', 'Готово к отгрузке'), ('Отгружено', 'Отгружено')], default='Перемещено', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.carrier'),
        ),
    ]
