# Generated by Django 4.1 on 2025-02-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carrier_pallet_status_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.doc'),
        ),
        migrations.AddField(
            model_name='product',
            name='permit_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер разрешения'),
        ),
        migrations.AddField(
            model_name='product',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.recipient'),
        ),
    ]
