# Generated by Django 4.1 on 2025-02-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_doc_product_permit_number_product_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='pallet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='permit_number',
        ),
        migrations.AddField(
            model_name='product',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.notice', verbose_name='Номер уведомления'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_dispatched',
            field=models.IntegerField(default=0, verbose_name='Отгружено'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='doc_code',
            field=models.CharField(choices=[('02013', 'Железнодорожная накладная'), ('02014', 'Иные документы, предусмотренные правилами перевозки по железной дороге'), ('02015', 'Транспортная накладная, предусмотренная Конвенцией о договоре международной дорожной перевозки грузов 1956 года'), ('02016', 'Иная транспортная накладная, используемая при перевозке товаров автодорожным транспортом\t'), ('02024', 'Книжка МДП'), ('02025', 'Карнет АТА'), ('04021', 'Счет-фактура (инвойс) к договору'), ('04025', 'Счет-проформа к договору\t'), ('04131', 'Отгрузочный (упаковочный) лист'), ('04023', 'Банковские документы, а также другие платежные документы, отражающие стоимость товара'), ('03011', 'Договор (контракт), заключенный при совершении сделки с товарами'), ('09013', 'Транзитная декларация'), ('09035', 'Декларация на товары'), ('09999', 'Иные транспортные документы')], max_length=5, verbose_name='Код документа'),
        ),
        migrations.AlterField(
            model_name='logplace',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='current_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущий вес (кг)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.doc', verbose_name='DOC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.place'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_product',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Код товара (EAN-13)'),
        ),
        migrations.AlterField(
            model_name='typeplace',
            name='max_size',
            field=models.CharField(max_length=100, verbose_name='Максимальный размер (кг)'),
        ),
        migrations.AlterField(
            model_name='typeplace',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальный вес (кг)'),
        ),
    ]
