# Generated by Django 4.1 on 2025-02-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_pallet_max_weight_remove_pallet_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrier',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='carrier',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='code_product',
            field=models.CharField(default=2, max_length=100, verbose_name='Код товара с документа (CMR/INVOICE)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier_name',
            field=models.CharField(max_length=100, verbose_name='ФИО водителя (перевозчик)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.supplier', verbose_name='Отправитель / Получатель (Поставщик)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_product',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Штрихкод EAN-13'),
        ),
    ]
